### ISSUE TITLE
extra value in install

### ISSUE THREAD

**Issue by proseLA** [CcMarc/AbuseIPDB#2]
```
PHP Fatal error: 1136:Column count doesn't match value count at row 12 ::
```

https://github.com/CcMarc/AbuseIPDB/blob/2b87ced35920778da101f45be3ba57bae39ec0f1/admin/includes/init_includes/init_abuseipdb_observer.php#L75

there are 10 values here when the insert statement is only requesting 9.  it looks like you have one `NULL` too many.

**Comment by CcMarc** [comment]
Fixed, Thank you!
