### ISSUE TITLE
ABUSEIPDB_LOG_FILE_FORMAT not used...

### ISSUE THREAD

**Issue by proseLA** [CcMarc/AbuseIPDB#4]
the constant/config value `ABUSEIPDB_LOG_FILE_FORMAT` is not used.

being a bit of a sysAdmin, i am NOT a fan of using `Y-m` or the like in file naming and it would be nice to not have it to use it.  for historical reference of this data, i use log rotate to keep however much data i deem necessary.

**Comment by CcMarc** [comment]
I have now added all the log file options to the admin interface, allowing you to customize them according to your preferences.
