### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jodsclass** [CcMarc/AbuseIPDB#7]
I've been using this plugin since your first version & it's great. I’ve had a feature request idea. Perhaps a blocked IP could be removed from the whos_online database table so blocked IPs don't fill up the who's online page of the admin.

Great plugin regardless.

**Comment by CcMarc** [comment]
I use enhanced whos_online hopefully it will work with your version of zencart, adding the following:

- Exclude IPs by AbuseIPDB Threshold: Automatically filter out IPs from the "Who's Online" list based on their AbuseIPDB score exceeding a set threshold.

- Display AbuseIPDB Score: Show the AbuseIPDB score next to each IP address in the "Who's Online" list, indicating the level of potential abuse associated with the IP.

- Shield Icon for Blocked IPs: Display a shield icon for IPs automatically blocked by the module, indicating they have met or exceeded the threshold.

- Ban Icon for Manual Blacklisting: Provide a ban icon that allows administrators to manually blacklist an IP address, adding it to the blacklist file directly from the "Who's Online" interface.

[AbuseIPDB_enhanced_whos_online_2.0.zip](https://github.com/user-attachments/files/16738144/AbuseIPDB_enhanced_whos_online_2.0.zip)
